// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace zhihuDaily.Model
{
    [DataContract]
    public class ReplyTo
    {
        [DataMember(Name = "content")]
        public string Content { get; set; }

        [DataMember(Name = "status")]
        public int Status { get; set; }

        [DataMember(Name = "id")]
        public int Id { get; set; }

        [DataMember(Name = "author")]
        public string Author { get; set; }
    }
    [DataContract]
    public class Comment
    {

        [DataMember(Name = "author")]
        public string Author { get; set; }

        [DataMember(Name = "content")]
        public string Content { get; set; }

        [DataMember(Name = "avatar")]
        public string Avatar { get; set; }

        [DataMember(Name = "time")]
        public int Time { get; set; }

        [DataMember(Name = "id")]
        public int Id { get; set; }

        [DataMember(Name = "likes")]
        public int Likes { get; set; }

        [DataMember(Name = "reply_to")]
        public ReplyTo ReplyTo { get; set; }

        public string ShowContent
        {
            get
            {
                string showContent = "";
                if (Content != null)
                {
                    showContent = Content;
                }
                if (ReplyTo != null)
                {
                    showContent += " //@" + ReplyTo.Author + "：" + ReplyTo.Content;
                }
                return showContent;
            }
        }
    }
    [DataContract]
    public class Comments
    {
        [DataMember(Name = "comments")]
        public IEnumerable<Comment> CommentList { get; set; }
    }
}
